#ifndef CONFIG_H_
#define CONFIG_H_

// SERIAL SETTINGS
#define BAUD 9600

// CHOICE OF MCU BOARDS TO DRIVE ROBOT. BY DEFAULT: 0 (MEGA2560)
#define BOARD_CHOICE MEGA2560

// ROBOT ARM LENGTH
#define LOW_SHANK_LENGTH 120.0
#define HIGH_SHANK_LENGTH 120.0

#define END_EFFECTOR_OFFSET                                                    \
  54.0 // LENGTH FROM UPPER SHANK BEARING TO MIDPOINT OF END EFFECTOR IN MM

// INITIAL INTERPOLATION SETTINGS
//   INITIAL_XYZ FORMS VERTICAL LOWER ARM & HORIZONTAL UPPER ARM IN 90 DEGREES
#define INITIAL_X 0.0 // CARTESIAN COORDINATE X
#define INITIAL_Y                                                              \
  (HIGH_SHANK_LENGTH + END_EFFECTOR_OFFSET) // CARTESIAN COORDINATE Y
#define INITIAL_Z LOW_SHANK_LENGTH          // CARTESIAN COORDINATE Z

#define INITIAL_E0 0.0 // RAIL STEPPER ENDSTOP POSITION

//  CALIBRATE HOME STEPS TO REACH DESIRED INITIAL_XYZ POSITIONS
#define X_HOME_STEPS 1600
#define Y_HOME_STEPS 600
#define Z_HOME_STEPS 3640 

// 1020 1900 3640 300

// HOMING SETTINGS:
#define HOME_X_STEPPER true  // "true" IF ENDSTOP IS INSTALLED
#define HOME_Y_STEPPER true  // "true" IF ENDSTOP IS INSTALLED
#define HOME_Z_STEPPER true  // "true" IF ENDSTOP IS INSTALLED
#define HOME_E0_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_ON_BOOT true    // "true" IF HOMING REQUIRED AFTER POWER ON

#define HOME_DWELL 1500 // INCREASE TO SLOW DOWN HOMING SPEED

// STEPPER SETTINGS:
#define MICROSTEPS 16            // MICROSTEPPING CONFIGURATION ON RAMPS1.4
#define STEPS_PER_REV 200        // NEMA17 STEPS PER REVOLUTION
#define INVERSE_X_STEPPER true   // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_Y_STEPPER false  // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_Z_STEPPER false  // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_E0_STEPPER false // CHANGE IF STEPPER MOVES OTHER WAY

// ENDSTOP SETTINGS:
#define X_MIN_INPUT 0  // OUTPUT VALUE WHEN SWITCH ACTIVATED
#define Y_MIN_INPUT 0  // OUTPUT VALUE WHEN SWITCH ACTIVATED
#define Z_MIN_INPUT 0  // OUTPUT VALUE WHEN SWITCH ACTIVATED
#define E0_MIN_INPUT 0 // OUTPUT VALUE WHEN SWITCH ACTIVATED

// GEAR RATIO SETTINGS
#define MOTOR_GEAR_TEETH                                                       \
  20.0 // 20.0 FOR 20SFFACTORY BELT VERSION   9.0 FOR FTOBLER GEAR VERSION
#define MAIN_GEAR_TEETH                                                        \
  90.0 // 90.0 FOR 20SFFACTORY BELT VERSION   32.0 FOR FTOBLER GEAR VERSION

#define SERVO_GRIP_DEGREE 45
#define SERVO_UNGRIP_DEGREE 130

// COMMAND QUEUE SETTINGS
#define QUEUE_SIZE 1

// PRINT REPLY SETTING
#define PRINT_REPLY true // "true" TO PRINT MSG AFTER ONE COMMAND IS PROCESSED
#define PRINT_REPLY_MSG                                                        \
  "ok" // MSG SENT FOR USER'S POST PROCESSING WITH OTHER SOFTWARE

// LOG SETTINGS
#define LOG_LEVEL 2
// 0: ERROR
// 1: INFO
// 2: DEBUG

#endif
